name: main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 12
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: ['3.12'] 

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                #   cache: 'pip'
                #   cache-dependency-path: '**/pyproject.toml' # Doesn't work!?

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip --editable .
                  python -m pip install -r requirements.txt

            - name: Check package installation
              run: |
                   python -c "import basis"

            - name: Check errors with 'ruff'
              run: |
                  ruff check .

            - name: Check format with 'ruff'
              run: |
                  ruff format .

            - name: Test the code
              run: |
                  python -m pip install -U pytest
                  python -X utf8 -m pytest tests